### ISSUE TITLE
どの言語のヘルプを表示するか選ぶことはできますか？

### ISSUE THREAD

**Issue by uga-rosa** [matsui54/ddu-source-help#3]
愛用しています。とても助かっています。

さて、
```vim
set helplang=ja,en
```
を設定しているのですが、日本語ヘルプと英語ヘルプの両方があるときでも英語の方を開きたいことがあります。source-paramsでhelplangを上書きすることができれば可能だと思うのですがどうでしょうか？

**Comment by matsui54** [comment]
提案ありがとうございます。
`helpLang` オプションによって`'helplang'`を上書きできるようにしました。
また`stype = "alllang"` とすることで複数の言語のタグがある場合に、その中から選べるようにしたのでよければ試してみてください。

**Comment by uga-rosa** [comment]
ありがとうございます！

**Comment by uga-rosa** [comment]
(コミット名typoしてますよん)
